### ISSUE TITLE
arrays_test  failed 

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/libpnicore#30]
Hi Eugen,

I've just tried to build one more the debian package and this time I get an error from tests:

      Start  4: types:conversion_test
 4/31 Test  #4: types:conversion_test ...................   Passed    0.06 sec
      Start  5: types:traits_test
 5/31 Test  #5: types:traits_test .......................   Passed    0.02 sec
      Start  6: arrays_test
 6/31 Test  #6: arrays_test .............................***Failed    1.55 sec
      Start  7: utils_test
 7/31 Test  #7: utils_test ..............................   Passed    0.04 sec

Any idea?
Log was deleted by pbuilder.

Cheers,
Jan

**Comment by jkotan** [comment]
It was on jessie and it happened only once.

**Comment by eugenwintersberger** [comment]
Ah. I can remember. This sometimes happens. It is an issue with the random number generator. Have not found a good solution for this.

**Comment by jkotan** [comment]
When the generated value is random it means random so one cannot be sure that is different. It may be the same so we cannot compare the values (unless we compare distribution with reasonable statistic).
