### ISSUE TITLE
make install requires documentation to be built

### ISSUE THREAD

**Issue by zjttoefs** [pni-libraries/libpnicore#5]
"make install" fails with an error when the documentation has not been built via "make doc". (build/doc/html missing)
It does appear to depend on a full compile and run through that.

Documentation could be made optional or required, not both. 

Since the code works fine without documentation I would suggest replacing the current error with a warning message. I don't want to have to install all of (pdf)latex everywhere.

**Comment by eugenwintersberger** [comment]
The way how the installation is done currently is definitely no good idea. As a solution I try to stick as close as possible to the GNU standard target definitions: 
make all -- builds only code
make pdf -- build the PDF documentation (currently only the users guide)
make html -- builds the html documentation (currently only the API documentation)

To install the software the following targets should be implemented 
make install -- install the code
make install-html -- install html documentation
make install-pdf -- install the PDF documentation

**Comment by eugenwintersberger** [comment]
So far the install-pdf and install-html targets work as expected. There is still a small flaw: the examples are always installed (even by the default 'install') target as the files are always present. Need a better solution here.

**Comment by eugenwintersberger** [comment]
There seems to be no quick and easy way to remove the examples installation from the default 'install' target. Any attempt to do so would make the behavior of the other two 'install' targets inconsistent. Since the example source files are mere files which have to be copied to the right location they can always be installed by the default 'install' target.
